### ISSUE TITLE
ARM Architecture Recommending a Single Worker

### ISSUE THREAD

**Issue by dmaislin-cribl** [criblio/criblsizing.info#320]
For the the architectures the sizing calculator is recommending a single worker for lower ingestion volumes such as 1TB in/out.  For redundancy, shouldn't the minimum be two workers?

<img width="1628" alt="Screenshot 2023-09-01 at 9 21 13 AM" src="https://github.com/bdalpe/criblsizing.info/assets/73345083/dbb17425-e645-470f-98a5-dc0ac539befb">

**Comment by SShah7433** [comment]
The next update will add an option for worker redundancy
