### ISSUE TITLE
Cribl outbound and inbound data volume as a different UI interface

### ISSUE THREAD

**Issue by arcsector** [criblio/criblsizing.info#456]
I think most people would prefer the outbound and inbound sliders to be either numerical text inputs, or another form of textual input so that the selection of size inbound/outbound is less difficult to select exactly. Currently the only way to accurately get 17 TB is to slide very carefully, or to use the arrow keys. If people could just plug in their number with their keyboard it would be much less painful.

**Comment by SShah7433** [comment]
Howdy! Appreciate the feedback! I completely agree! The update that includes this is already implemented (and merged into main). 

Should be published in the coming days!

Thanks!
